#!/bin/sh
set -e

action="$1"
shift

case "$action" in
	configure|triggered)
		if [ -f /usr/share/sddm/themes/breeze/Main.qml.bak ]
		then
			sed -E "s/x: geometry.*$/x: 0; y: 0; width: 3840; height: 2160/g" "/usr/share/sddm/themes/breeze/Main.qml.bak" > "/usr/share/sddm/themes/breeze/Main.qml"
		fi
		;;
esac

#DEBHELPER#

exit 0
